export type HelpGroup = 'Start here' | 'Understand your position' | 'Advanced planning' | 'Your data';

export interface HelpTopic {
  slug: string;
  title: string;
  group: HelpGroup;
  summary: string;
  keywords: string[];
  relatedSection: string;
  useful: string;
  steps: string[];
  example: string;
  results: string;
  mistakes: string[];
}

const topic = (value: HelpTopic): HelpTopic => value;

export const helpTopics: HelpTopic[] = [
  topic({ slug: 'getting-started', title: 'Getting started', group: 'Start here', summary: 'Set up a position, test an idea, and keep a backup.', keywords: ['beginner', 'setup', 'ticker', 'shares', 'average'], relatedSection: 'position', useful: 'Use this first if you are new to the calculator.', steps: ['Create a position and enter its ticker, shares currently owned, average price, and currency.', 'Set Buy and Sell fees separately, then optionally enter a current market price.', 'Test a buy or sale, add hypothetical rows to the future plan, and export a JSON backup when you want a copy.'], example: 'For 20 shares at $50, enter 20 and 50 before testing any new order.', results: 'Scenario tools and DCA ladders are optional advanced planning features. The calculator performs arithmetic and planning only.', mistakes: ['Do not treat a test transaction as a real trade.', 'Keep a JSON backup before clearing browser data.'] }),
  topic({ slug: 'positions', title: 'Positions and holdings', group: 'Start here', summary: 'Keep each ticker or holding in its own browser-local position.', keywords: ['position', 'holding', 'ticker', 'currency', 'delete'], relatedSection: 'position', useful: 'Use this when adding, switching, or editing a holding.', steps: ['Choose New position, then enter ticker, shares, average price, currency, budget, and share increment.', 'Use the position selector to switch holdings; each has its own settings and future plan.', 'Use Delete only when you no longer need that browser-local record.'], example: 'A position named ABC can hold 100 shares at an average price of $25 while another position keeps separate values.', results: 'Current market price is entered manually and is used only for market-value calculations.', mistakes: ['Deleting a position removes its saved data from this browser.', 'A share increment of 1 means whole shares; use a smaller increment only when fractional shares are allowed.'] }),
  topic({ slug: 'buy-sell', title: 'Testing a buy or sale', group: 'Start here', summary: 'Preview a fee-aware buy or sale without changing the saved position.', keywords: ['buy', 'sell', 'gross', 'total paid', 'net received', 'realized'], relatedSection: 'transaction', useful: 'Use this to see the arithmetic before adding a hypothetical row to a plan.', steps: ['Choose Buy or Sell and enter price, quantity, and the matching fee.', 'Read gross value, fee, total paid or net received, and the resulting position.', 'Add the result to the future plan only if you want to test it in sequence.'], example: 'Buying 10 shares at $40 adds the purchase cost and Buy fee to cost basis.', results: 'A Buy fee becomes part of cost basis. A Sell fee reduces net proceeds and realized profit or loss. A partial sale leaves the remaining average unchanged under this average-cost method.', mistakes: ['Testing does not change the saved position.', 'Do not sell more shares than the position or prior plan rows make available.'] }),
  topic({ slug: 'fees', title: 'Fees', group: 'Start here', summary: 'Choose a percentage or fixed fee for buys and separately for sales.', keywords: ['fee', 'percentage', 'fixed', 'commission', 'cost basis'], relatedSection: 'transaction', useful: 'Use this when your broker charges commissions or percentage-based fees.', steps: ['Choose Percent or Fixed in the Buy or Sell controls.', 'Enter a non-negative fee value.', 'Review the fee shown beside the transaction before using its result.'], example: '10 shares × $100 = $1,000. At 0.2%, the fee is $2 and a buy totals $1,002. With a $10 fixed fee, the buy totals $1,010.', results: 'Buy and Sell keep separate settings. Buy fees raise cost basis; Sell fees reduce net proceeds.', mistakes: ['Do not enter 0.2 when you mean 20%.', 'Taxes and broker charges you do not enter are not included.'] }),
  topic({ slug: 'market-snapshot', title: 'Current market snapshot', group: 'Understand your position', summary: 'Read current value, estimated liquidation value, and break-even from a manual price.', keywords: ['market', 'snapshot', 'unrealized', 'liquidation', 'break-even'], relatedSection: 'market-snapshot', useful: 'Use this after entering a current market price.', steps: ['Enter the current market price in Current holding.', 'Open Position snapshot.', 'Compare gross and after-fee values, then inspect the after-plan result if you have future rows.'], example: 'If 100 shares have a $50 average and the market price is $60, gross value is $6,000 before any estimated sell fee.', results: 'Gross unrealized P/L ignores the sell fee. Net liquidation value and net unrealized P/L include it. Break-even is the estimated price needed to cover average cost and the configured sell fee.', mistakes: ['The app does not fetch a live market price.', 'Realized P/L from planned sales is separate from unrealized P/L on remaining shares.'] }),
  topic({ slug: 'target-tools', title: 'Target tools', group: 'Understand your position', summary: 'Work backward from a desired average, break-even, profit, or return target.', keywords: ['target', 'average', 'profit', 'return', 'break-even'], relatedSection: 'target-tools', useful: 'Use this to estimate a buy size or sale price without changing your position.', steps: ['For Target average, enter desired average and buy price; optionally respect the budget.', 'For exit tools, enter shares to sell and choose break-even, profit, or return.', 'Read required shares or sale price and the resulting average or net proceeds.'], example: 'A target average of $45 from 100 shares at $50 and a $40 buy price needs a calculated additional quantity.', results: 'An impossible target is shown instead of forcing an answer. Target calculations are read-only.', mistakes: ['A lower target average must be above the fee-adjusted purchase price to be reachable.', 'Running a target calculation does not modify the saved position.'] }),
  topic({ slug: 'buying-guide', title: 'Buying guide and efficiency', group: 'Understand your position', summary: 'Compare smaller and full-budget buys and understand diminishing average-price effects.', keywords: ['buying guide', 'efficiency', 'budget', 'possible drop', 'next share'], relatedSection: 'buying-guide', useful: 'Use this to understand how different buy sizes move the arithmetic average.', steps: ['Set maximum budget, buy price, share increment, and the two usefulness controls.', 'Review the smaller efficient buy and full-budget result.', 'Compare different quantities in the buy-size section.'], example: 'Possible drop reached is how much of the distance between the current average and new buy price has already been covered.', results: 'Next-share usefulness compares the next added share with the first. The useful stopping reference shows where extra shares have become much less effective. Full-budget benefit compares a smaller buy with the complete entered budget.', mistakes: ['Buying more normally moves the average closer to buy price, but each extra share usually has a smaller effect.', 'A more efficient average reduction does not mean an investment is safer or better.'] }),
  topic({ slug: 'future-plan', title: 'Future transaction plan', group: 'Start here', summary: 'Chain hypothetical buys and sales in the order you expect them to happen.', keywords: ['future plan', 'sequential', 'planned', 'csv', 'remove'], relatedSection: 'future-plan', useful: 'Use this to see a sequence rather than one isolated transaction.', steps: ['Test a transaction and choose Add to plan.', 'Read each row from top to bottom: each begins from the previous row’s result.', 'Remove a row or export plan CSV when needed.'], example: 'A buy followed by a sale uses the new average and share count created by the buy.', results: 'Rows show gross value, fee, total paid or net received, shares after, average after, and sale realized P/L.', mistakes: ['The ordinary future plan is hypothetical and does not change the saved position.', 'Order matters.'] }),
  topic({ slug: 'scenario-planner', title: 'Scenario Planner', group: 'Advanced planning', summary: 'Use a sandbox for detailed plans without changing What you own now.', keywords: ['scenario', 'sandbox', 'draft', 'active', 'archive'], relatedSection: 'scenario-planner', useful: 'Use this for ideas that need their own rows, market price, notes, and status.', steps: ['Create a scenario or save the current plan as a scenario.', 'Name it, set its market price and status, then add ladder or transaction rows.', 'Duplicate, archive, restore, or delete from Saved scenarios when appropriate.'], example: 'A scenario can model a staged buy plan while the saved position remains 20 shares at $50.', results: 'Draft is work in progress, Active is ready to compare, Completed records a finished idea, and Archived hides an older scenario from ordinary comparison.', mistakes: ['Loading a scenario changes only the planner workspace; it does not overwrite the real saved position.', 'Save or duplicate intentionally before changing a plan you want to keep.'] }),
  topic({ slug: 'dca-ladder', title: 'DCA Ladder', group: 'Advanced planning', summary: 'Generate fee-aware staged buy levels inside a scenario.', keywords: ['dca', 'ladder', 'levels', 'equal cash', 'equal shares', 'unallocated'], relatedSection: 'dca-ladder', useful: 'Use this for a planned sequence of buy prices and quantities.', steps: ['Choose 2–20 levels, start/end prices, spacing, distribution, fees, and precision.', 'Generate the ladder, then edit individual price, quantity, or fee rows.', 'Read cumulative quantity, basis, average, fee, and all-in cost before treating rows as planned scenario data.'], example: 'For 20 shares at $50 and a $1,000 all-in budget, levels at $40, $35, and $30 divide the budget with fees included and round quantities down.', results: 'Linear spacing changes price by equal amounts; equal-percentage spacing changes it by equal percentages. Equal cash uses the all-in budget, equal shares distributes total shares, and Custom keeps explicit row quantities. Unallocated remainder cannot buy another permitted share amount.', mistakes: ['Generated rows remain planning data until used in a scenario and later marked Executed.', 'Maximum capital requirement is the most cash needed before later sales release money.'] }),
  topic({ slug: 'saved-scenarios', title: 'Saved Scenarios', group: 'Advanced planning', summary: 'Manage scenarios attached to the active position.', keywords: ['saved', 'duplicate', 'archive', 'restore', 'delete'], relatedSection: 'saved-scenarios', useful: 'Use this to return to, copy, archive, or remove a saved sandbox.', steps: ['Switch to the position whose scenarios you want to see.', 'Load or duplicate a scenario, or archive it when it is no longer part of normal comparison.', 'Restore or delete it deliberately when needed.'], example: 'Two scenarios may share the same name but remain separate saved ideas.', results: 'Archived scenarios are hidden from ordinary comparison until restored.', mistakes: ['Delete removes the scenario from this browser.', 'A scenario belongs to its attached position, not every holding.'] }),
  topic({ slug: 'scenario-comparison', title: 'Scenario comparison', group: 'Advanced planning', summary: 'Compare up to four non-archived scenario outcomes side by side.', keywords: ['compare', 'capital', 'fees', 'realized', 'unrealized'], relatedSection: 'scenario-comparison', useful: 'Use this when you want to compare arithmetic trade-offs between plans.', steps: ['Select Compare on up to four active scenarios.', 'Open comparison and review shares, average, fees, value, P/L, and break-even.', 'Remove a scenario or clear the comparison when finished.'], example: 'One plan may reach a lower average but need much more cash and create a larger position.', results: 'Maximum capital requirement means the most cash the scenario needs at any point before later sales release money.', mistakes: ['A lower average is not automatically a better result.', 'Archived scenarios cannot be selected until restored.'] }),
  topic({ slug: 'reverse-sell', title: 'Reverse Sell Planner', group: 'Advanced planning', summary: 'Solve for sale price from quantity, or quantity from sale price.', keywords: ['reverse sell', 'net proceeds', 'quantity', 'price', 'oversell'], relatedSection: 'reverse-sell', useful: 'Use this to plan an exit target after the configured Sell fee.', steps: ['Choose Solve price and enter quantity for break-even, profit, return, or net proceeds.', 'Or choose Solve shares, enter sale price, then set currency-profit or net-proceeds target.', 'Review rounded quantity, fee, net proceeds, realized P/L, and remaining shares.'], example: 'At a known price, a required quantity is rounded up to the share increment when a valid target needs it.', results: 'Oversells, invalid fees, and impossible targets are rejected. Target return at a known price reports achieved return rather than inventing an arbitrary share quantity.', mistakes: ['Fees can make a target unreachable at the entered price.', 'Do not use a quantity greater than available shares.'] }),
  topic({ slug: 'stress-tests', title: 'Stress tests', group: 'Advanced planning', summary: 'See scenario arithmetic at several manual price points.', keywords: ['stress', 'price', 'percentage', 'sort', 'forecast'], relatedSection: 'stress-tests', useful: 'Use this to compare values and P/L at simple what-if prices.', steps: ['Use the default percentage changes or add an absolute price.', 'Reset defaults or sort the displayed entries.', 'Read market value, realized P/L, unrealized P/L, total P/L, return, and break-even distance.'], example: 'A −30% entry applies a 30% decrease to the scenario market price; an absolute entry uses the exact price you enter.', results: 'The current test point is based on the scenario market price.', mistakes: ['Stress tests are arithmetic examples, not market forecasts.', 'Enter a scenario market price first for percentage entries to be useful.'] }),
  topic({ slug: 'executed-transactions', title: 'Executed transactions', group: 'Advanced planning', summary: 'Record what happened, preview it, and explicitly apply it to the saved position.', keywords: ['executed', 'cancelled', 'actual', 'apply', 'broker'], relatedSection: 'executed-transactions', useful: 'Use this after real trades that correspond to a scenario.', steps: ['Mark relevant rows Executed and enter actual price, quantity, fee override, date, note, or broker label.', 'Open the application preview and review eligible and skipped rows plus resulting shares and average.', 'Confirm only when the preview is correct.'], example: 'An actual currency fee override replaces the planned fee for that executed row.', results: 'Planned rows remain hypothetical. Cancelled rows are excluded. Applying executed transactions changes the saved position and marks applied rows so they cannot be applied again.', mistakes: ['An invalid oversell blocks the complete application.', 'The operation applies all eligible valid rows together, while scenario history remains available.'] }),
  topic({ slug: 'backup-export', title: 'Backup and exports', group: 'Your data', summary: 'Export browser-local data, preview imports, and create CSV views.', keywords: ['backup', 'json', 'csv', 'merge', 'replace', 'restore'], relatedSection: 'data-management', useful: 'Use this regularly to keep a copy outside the browser.', steps: ['Export all positions or the active position as JSON.', 'When importing, review positions, plans, scenarios, transactions, executed, and applied counts before choosing Merge or Replace.', 'Use plan, scenario, and DCA Ladder CSV files for viewing or external analysis.'], example: 'Merge keeps current browser data and adds imported data safely; Replace removes current browser data and uses the backup after confirmation.', results: 'CSV import is not supported. JSON is the complete backup format.', mistakes: ['Export a JSON backup periodically.', 'Replace is destructive to current browser-local data.'] }),
  topic({ slug: 'privacy', title: 'Browser storage and privacy', group: 'Your data', summary: 'Understand where the app saves records and what a backup protects.', keywords: ['privacy', 'localstorage', 'browser', 'github', 'device'], relatedSection: 'data-management', useful: 'Use this before relying on a browser as your only copy.', steps: ['Keep a JSON backup outside the browser.', 'Use the same browser profile and website origin when returning to saved data.', 'Export before clearing site data or changing devices.'], example: 'Another browser or device starts with separate calculator data.', results: 'Positions, plans, and scenarios are stored in browser localStorage. There is no portfolio backend or account system, and the app does not upload saved portfolio records to a portfolio server. GitHub serves application files and receives normal website requests.', mistakes: ['Private or incognito sessions may be temporary.', 'Clearing website data may delete saved calculator information.'] }),
  topic({ slug: 'glossary', title: 'Glossary', group: 'Your data', summary: 'Plain definitions for common calculator terms.', keywords: ['definition', 'cost basis', 'dca', 'break-even', 'unallocated'], relatedSection: 'position', useful: 'Use this whenever a label needs a quick explanation.', steps: ['Read the term in the list below.', 'Return to its related calculator section when you are ready.'], example: 'Cost basis is the money assigned to the shares you still own, including configured Buy fees.', results: 'Position: shares you own. Cost basis: money assigned to shares still owned. Average price: cost basis per share. Current market price: the price you enter for estimates. Market value: shares × entered market price. Gross value: before fee. Fee: the trading charge used in the calculation. Percentage fee: a percentage of gross value. Fixed fee: an entered currency amount. Net proceeds: sale value after fee. Total paid: buy gross value plus fee. Realized P/L: result on sold shares. Unrealized P/L: result on still-owned shares. DCA: staged buying. DCA level: one planned price and quantity. Target average: the desired average after a planned buy. Break-even: estimated no-profit/no-loss sale price. Share increment: smallest permitted quantity. Scenario: sandbox plan. Scenario workspace: the currently displayed scenario plan. Stress test: a saved price change used to estimate outcomes. Planned, Executed, Cancelled, and Applied describe transaction progress. Unallocated remainder is cash that cannot buy another permitted increment. Maximum capital requirement is the highest cash need before later sales.', mistakes: ['Definitions explain arithmetic only; they are not investing advice.'] }),
];

export const helpGroups: HelpGroup[] = ['Start here', 'Understand your position', 'Advanced planning', 'Your data'];

export function findHelpTopic(slug: string): HelpTopic | undefined {
  return helpTopics.find((item) => item.slug === slug);
}
