import type { HelpBlock, HelpGroup, HelpTopic } from './help-types';

export type { HelpBlock, HelpGroup, HelpTopic } from './help-types';

const topic = (value: HelpTopic): HelpTopic => value;
const paragraph = (text: string): HelpBlock => ({ type: 'paragraph', text });
const steps = (items: string[], title?: string): HelpBlock => ({ type: 'steps', title, items });
const example = (title: string, rows: Array<{ label: string; value: string }>, intro?: string, text?: string[]): HelpBlock => ({ type: 'example', title, rows, intro, text });
const results = (items: Array<{ term: string; explanation: string }>, title?: string): HelpBlock => ({ type: 'result-list', title, items });
const topics = (slugs: string[], title?: string): HelpBlock => ({ type: 'topics', slugs, title });
const note = (text: string, title?: string): HelpBlock => ({ type: 'note', text, title });
const warning = (text: string, title?: string): HelpBlock => ({ type: 'warning', text, title });
const mistakes = (items: string[]): HelpBlock => ({ type: 'mistakes', items });

export const helpTopics: HelpTopic[] = [
  topic({ slug: 'getting-started', title: 'Getting started', group: 'New users', summary: 'A beginner path from a saved position to a safe browser backup.', keywords: ['beginner', 'setup', 'ticker', 'buy', 'results', 'backup'], relatedSection: 'position', blocks: [
    paragraph('Use the calculator one step at a time. You do not need the advanced planner to test a buy or a sale.'),
    steps(['Create a position, then enter its ticker or name.', 'Enter shares currently owned, the average buy price, and a currency.', 'Set Buy and Sell fees separately. Enter a current market price only if you want current-value estimates.', 'Test one Buy or Sell and read the result before adding anything to a plan.', 'Add a row to the ordinary future plan only when you want to test a hypothetical sequence.', 'Export a JSON backup after entering information you want to keep.'], 'A simple first session'),
    results([{ term: 'Tested transaction', explanation: 'Shows arithmetic only. It does not modify the saved holding.' }, { term: 'Ordinary future plan', explanation: 'A hypothetical sequence. It is still not a trade or a position update.' }, { term: 'Scenario Planner and DCA Ladder', explanation: 'Optional advanced tools for separate planning ideas.' }, { term: 'Apply Executed Transactions', explanation: 'The separate confirmation flow that can update the saved position after real trades are recorded.' }], 'What changes and what does not'),
    topics(['positions', 'buy-sell', 'reading-results', 'backup-export'], 'Continue learning'),
    mistakes(['Keep a JSON backup before clearing browser data or moving to another browser profile.', 'Do not treat a calculator result as financial advice or a recommendation.']),
  ] }),
  topic({ slug: 'positions', title: 'Positions and holdings', group: 'New users', summary: 'Set up a browser-local record for what you own now and the planning controls around it.', keywords: ['position', 'holding', 'ticker', 'shares', 'average buy price', 'market value', 'budget', 'share increment', 'delete'], relatedSection: 'position', blocks: [
    paragraph('A position is the saved starting point for one holding. Each position has its own currency, fees, ordinary plan, and scenarios.'),
    example('Position example', [{ label: 'Ticker', value: 'ABC' }, { label: 'Shares owned', value: '20' }, { label: 'Average buy price', value: '$50' }, { label: 'Cost basis', value: '$1,000' }, { label: 'Current market price', value: '$45' }, { label: 'Current market value', value: '$900' }], 'Cost basis is 20 × $50. Market value is 20 × the manually entered $45 price.'),
    results([{ term: 'Shares owned', explanation: 'The quantity currently held in the saved position.' }, { term: 'Average buy price', explanation: 'Historical cost per share for the position. It is not a live quote.' }, { term: 'Current market price', explanation: 'A manual estimate for market-value and P/L calculations. Changing it does not change the average buy price.' }, { term: 'Maximum budget', explanation: 'A planning limit for calculator comparisons. The app does not track cash.' }, { term: 'Share increment', explanation: 'The smallest permitted quantity. Use 1 for whole shares or 0.01 when fractional shares are allowed.' }]),
    warning('Deleting a position removes that position and its browser-local data. Export a JSON backup first if you may need it later.', 'Before deleting'),
  ] }),
  topic({ slug: 'buy-sell', title: 'Testing a buy or sale', group: 'New users', summary: 'Preview one fee-aware transaction without changing the saved position.', keywords: ['buy', 'sell', 'gross purchase', 'gross sale', 'total paid', 'net received', 'realized profit', 'cost basis'], relatedSection: 'transaction', blocks: [
    paragraph('Choose Buy or Sell, enter a price, quantity, and the matching fee. The result is a preview until you add it to a hypothetical plan or later apply recorded executed trades.'),
    example('Buy with a percentage fee', [{ label: 'Current position', value: '100 shares at $50 average' }, { label: 'Buy', value: '10 shares at $40' }, { label: 'Buy fee', value: '0.2%' }, { label: 'Gross purchase', value: '$400' }, { label: 'Fee', value: '$0.80' }, { label: 'Total paid', value: '$400.80' }, { label: 'New cost basis', value: '$5,400.80' }, { label: 'New average', value: 'about $49.10' }], 'The Buy fee is included in the new cost basis.'),
    example('Sale with a fixed fee', [{ label: 'Current position', value: '100 shares at $50 average' }, { label: 'Sell', value: '10 shares at $60' }, { label: 'Fixed Sell fee', value: '$10' }, { label: 'Gross sale', value: '$600' }, { label: 'Net received', value: '$590' }, { label: 'Cost basis of sold shares', value: '$500' }, { label: 'Realized profit', value: '$90' }, { label: 'Remaining average', value: '$50' }], 'Under the calculator’s average-cost method, a partial sale keeps the remaining average unchanged.'),
    note('Testing a transaction does not modify the saved position. Adding it to the ordinary plan keeps it hypothetical.', 'Important'),
  ] }),
  topic({ slug: 'reading-results', title: 'Reading the results', group: 'New users', summary: 'Understand the common labels shown after a tested buy, sale, plan, or scenario.', keywords: ['gross value', 'fee', 'total paid', 'net received', 'shares after', 'average after', 'cost basis', 'realized', 'unrealized', 'break-even', 'market value', 'required cash', 'remaining shares'], relatedSection: 'transaction', blocks: [
    paragraph('The calculator uses the same result terms in several sections. Read the label together with whether the row is a Buy, Sell, current position, or hypothetical plan.'),
    example('Tested Buy: 10 shares at $50 average, then buy 2 at $40 with a $2 fixed fee', [{ label: 'Gross purchase', value: '$80' }, { label: 'Fee', value: '$2' }, { label: 'Total paid', value: '$82' }, { label: 'Existing cost basis', value: '$500' }, { label: 'New cost basis', value: '$582' }, { label: 'New shares', value: '12' }, { label: 'New average', value: '$48.50' }]),
    example('Simple partial sale', [{ label: 'Sell', value: '2 shares at $60' }, { label: 'Gross sale value', value: '$120' }, { label: 'Sell fee', value: '$2' }, { label: 'Net received', value: '$118' }, { label: 'Cost basis of sold shares', value: '$100' }, { label: 'Realized P/L', value: '$18' }, { label: 'Remaining shares', value: '8 at the same $50 average' }], 'A partial sale realizes a result on the shares sold; it does not reprice the shares that remain.'),
    results([{ term: 'Gross value', explanation: 'Price × quantity before a fee.' }, { term: 'Fee', explanation: 'The configured percentage or fixed charge used for that calculation.' }, { term: 'Total paid / required cash', explanation: 'A Buy’s gross value plus fee.' }, { term: 'Net received', explanation: 'A Sell’s gross value minus fee.' }, { term: 'Shares after / remaining shares', explanation: 'The quantity left after the row or result.' }, { term: 'Average after / average lowered', explanation: 'The average cost after a Buy or planned sequence, and its change from before.' }, { term: 'Cost basis', explanation: 'The assigned cost of shares still owned, including configured Buy fees.' }, { term: 'Realized P/L', explanation: 'The gain or loss on sold shares after the Sell fee.' }, { term: 'Unrealized P/L', explanation: 'The estimated result on shares still owned at the entered market price.' }, { term: 'Gross result / after-fee result', explanation: 'The before-fee result versus the estimate after configured fees.' }, { term: 'Break-even', explanation: 'The estimated price where net sale proceeds cover the relevant cost basis.' }, { term: 'Market value', explanation: 'Shares × entered current market price.' }]),
  ] }),
  topic({ slug: 'fees', title: 'Fees', group: 'New users', summary: 'Set separate Buy and Sell fees and see how they change cost basis or net proceeds.', keywords: ['fee', 'percentage fee', 'fixed fee', '0.2 percent', 'commission', 'taxes', 'total paid', 'net proceeds'], relatedSection: 'transaction', blocks: [
    paragraph('Choose Percent when a fee is a percentage of gross value. Choose Fixed when it is one currency amount for the whole transaction.'),
    example('Percentage versus fixed', [{ label: '10 shares × $100', value: '$1,000 gross value' }, { label: '0.2% fee', value: '$2' }, { label: 'Buy total with 0.2%', value: '$1,002' }, { label: '$10 fixed fee', value: '$10 once' }, { label: 'Buy total with fixed fee', value: '$1,010' }]),
    results([{ term: 'Buy fee', explanation: 'Added to total paid and cost basis.' }, { term: 'Sell fee', explanation: 'Subtracted from gross sale value and net proceeds.' }, { term: 'Percent input', explanation: '0.2 in Percent mode means 0.2%, not 20%.' }, { term: 'Fixed input', explanation: 'Applied once to that transaction, not once per share.' }]),
    note('Buy and Sell settings are separate. Taxes and charges you do not enter are not included.'),
  ] }),
  topic({ slug: 'market-snapshot', title: 'Current market snapshot', group: 'Understand your position', summary: 'Compare current gross value, estimated after-fee value, and break-even using a manual market price.', keywords: ['market snapshot', 'market value', 'liquidation value', 'gross unrealized', 'net unrealized', 'break-even', 'live price'], relatedSection: 'market-snapshot', blocks: [
    paragraph('The snapshot uses the current market price you enter. It is an estimate; the application does not fetch a live quote.'),
    example('Current-value example', [{ label: 'Position', value: '100 shares at $50 average' }, { label: 'Current market price', value: '$60' }, { label: 'Sell fee', value: '0.2%' }, { label: 'Cost basis', value: '$5,000' }, { label: 'Gross market value', value: '$6,000' }, { label: 'Gross unrealized profit', value: '$1,000' }, { label: 'Estimated Sell fee', value: '$12' }, { label: 'Estimated net liquidation value', value: '$5,988' }, { label: 'Net unrealized profit', value: '$988' }]),
    results([{ term: 'Gross and after-fee values', explanation: 'Gross ignores the estimated Sell fee; after-fee values include it.' }, { term: 'Realized and unrealized P/L', explanation: 'Realized P/L comes from sales. Unrealized P/L is an estimate on shares still owned.' }, { term: 'Current and after-plan result', explanation: 'Current reflects the saved position; after-plan reflects a hypothetical sequence.' }, { term: 'Current price and break-even', explanation: 'Current price is your entered estimate. Break-even is the estimated fee-aware sale price needed to cover cost.' }]),
  ] }),
  topic({ slug: 'target-tools', title: 'Target tools', group: 'Understand your position', summary: 'Work backward from a target average, break-even, profit, or return without changing the saved position.', keywords: ['target average', 'break even', 'profit target', 'required shares', 'required price', 'rounding'], relatedSection: 'target-tools', blocks: [
    example('Target average', [{ label: 'Current position', value: '100 shares at $50' }, { label: 'Planned Buy price', value: '$40' }, { label: 'Target average', value: '$45' }], 'The calculator works backward to find a required quantity. Buy fees can increase it, and the quantity is rounded upward to the configured share increment.'),
    example('Exit targets', [{ label: 'Current average', value: '$50' }, { label: 'Sell fee', value: '0.2%' }, { label: 'Break-even result', value: 'Slightly above $50' }, { label: 'Profit example', value: 'Sell 40 shares for a $500 realized-profit target' }], 'The required sale price considers the cost basis of the shares sold and the fee.'),
    results([{ term: 'Target average', explanation: 'A target at or below the fee-adjusted Buy price is impossible.' }, { term: 'Rounding', explanation: 'The actual resulting average can be slightly below the requested target after quantity is rounded up.' }, { term: 'Read-only calculation', explanation: 'Running either target tool does not update the saved position.' }]),
  ] }),
  topic({ slug: 'buying-guide', title: 'Buying guide and diminishing returns', group: 'Understand your position', summary: 'See why each additional share usually moves an average less than the one before it.', keywords: ['diminishing returns', 'available average reduction', 'effect of one more share', 'diminishing-return reference', 'halfway toward the buy price', 'full-budget comparison'], relatedSection: 'buying-guide', blocks: [
    paragraph('When the Buy price is below the current average, buying more moves the average toward that Buy price. The movement is not linear: each extra share normally has less effect than the previous one.'),
    example('No-fee diminishing-return example', [{ label: 'Starting position', value: '100 shares at $50 average' }, { label: 'Buy price', value: '$40' }, { label: 'Maximum theoretical average reduction', value: '$10' }], 'The following values are arithmetic comparisons, not purchase recommendations.'),
    example('Buy 25 shares', [{ label: 'New average', value: '$48.00' }, { label: 'Average lowered', value: '$2.00' }, { label: 'Available reduction reached', value: '20%' }]),
    example('Buy 50 shares', [{ label: 'New average', value: '$46.67' }, { label: 'Average lowered', value: '$3.33' }, { label: 'Available reduction reached', value: '33.3%' }]),
    example('Buy 100 shares', [{ label: 'New average', value: '$45.00' }, { label: 'Average lowered', value: '$5.00' }, { label: 'Available reduction reached', value: '50%' }]),
    example('Buy 200 shares', [{ label: 'New average', value: '$43.33' }, { label: 'Average lowered', value: '$6.67' }, { label: 'Available reduction reached', value: '66.7%' }]),
    paragraph('The first 100 extra shares lower the average by $5. The next 100 lower it by only another $1.67. The average approaches $40 but cannot reach it exactly through a finite purchase at that same price.'),
    results([{ term: 'Available average reduction reached', explanation: 'How much of the maximum movement toward the Buy price has already occurred.' }, { term: 'Effect of one more share', explanation: 'The next share’s effect compared with the first additional share.' }, { term: 'Diminishing-return reference', explanation: 'A calculated point where each later share has become much less effective.' }, { term: 'Halfway toward the buy price', explanation: 'The quantity that moves the average through half the available distance.' }, { term: 'Smaller buy with similar benefit', explanation: 'The smallest calculated purchase that reaches the selected share of the full-budget average reduction.' }, { term: 'Full-budget comparison', explanation: 'The result of using the complete budget, including configured Buy fees.' }]),
    warning('These values compare average-price arithmetic. They do not measure investment quality, risk, or likelihood of price recovery.'),
  ] }),
  topic({ slug: 'future-plan', title: 'Future transaction plan', group: 'New users', summary: 'Test a sequence of hypothetical buys and sales in the order they would occur.', keywords: ['future plan', 'ordinary plan', 'sequential', 'planned transaction', 'csv', 'hypothetical'], relatedSection: 'future-plan', blocks: [
    example('Sequential plan', [{ label: 'Starting position', value: '100 shares at $50' }, { label: 'Row 1', value: 'Buy 20 at $40' }, { label: 'Row 2', value: 'Sell 10 at $60' }], 'Row 1 starts from the saved position. Row 2 starts from Row 1’s result.'),
    results([{ term: 'Order matters', explanation: 'Changing or removing an earlier row changes every later result.' }, { term: 'Buy fee', explanation: 'Changes the cost basis and later average price.' }, { term: 'Sell fee', explanation: 'Changes net proceeds and realized P/L.' }, { term: 'CSV export', explanation: 'Creates a readable export. It does not apply transactions.' }]),
    note('Testing one transaction is isolated. Adding it to the ordinary future plan makes it part of a hypothetical sequence. Saving as a scenario creates a separate planning record; applying executed scenario transactions is the separate step that can update the saved position.'),
  ] }),
  topic({ slug: 'scenario-planner', title: 'Scenario Planner', group: 'Advanced planning', summary: 'Use a named planning sandbox for transactions, ladders, stress tests, and recorded execution details.', keywords: ['saved position', 'ordinary future plan', 'scenario workspace', 'saved scenario', 'sandbox', 'draft', 'active', 'archive'], relatedSection: 'scenario-planner', blocks: [
    results([{ term: 'Saved position', explanation: 'The shares and average stored under What you own now.' }, { term: 'Ordinary future plan', explanation: 'A hypothetical sequence attached to the saved position.' }, { term: 'Scenario workspace', explanation: 'The scenario currently open in the planner.' }, { term: 'Saved scenario', explanation: 'A named, browser-local planning record attached to one position.' }], 'Four separate layers'),
    example('Separate planning ideas', [{ label: 'Saved position', value: '20 shares at $50' }, { label: 'Ordinary plan', value: 'Buy 5 at $40' }, { label: 'Scenario A', value: 'Buy 5 at $40, then 10 at $35' }, { label: 'Scenario B', value: 'Wait and buy 15 at $30' }]),
    results([{ term: 'Load', explanation: 'Opens a scenario in the planner without changing the saved 20-share position.' }, { term: 'Edit and duplicate', explanation: 'Changes made to the loaded scenario are saved in this browser; use Duplicate first when you need an independent copy.' }, { term: 'Archive and restore', explanation: 'Archived scenarios remain stored but are hidden from ordinary comparison until restored.' }, { term: 'Delete', explanation: 'Removes that scenario from this browser.' }]),
    warning('A scenario is a sandbox. It becomes part of the saved holding only through the separate Apply Executed Transactions process.'),
  ] }),
  topic({ slug: 'dca-ladder', title: 'DCA Ladder', group: 'Advanced planning', summary: 'Divide a planned purchase into fee-aware levels at different prices inside a scenario.', keywords: ['dca', 'ladder', 'linear spacing', 'equal percentage', 'equal cash', 'equal shares', 'custom quantities', 'unallocated remainder', 'maximum capital requirement'], relatedSection: 'dca-ladder', blocks: [
    paragraph('DCA means dividing a planned purchase into several smaller orders, often at different prices. It is planning arithmetic, not a forecast or an order-routing tool.'),
    results([{ term: 'Levels, start price, and end price', explanation: 'Choose how many staged orders and the range of prices.' }, { term: 'Linear / equal-percentage spacing', explanation: 'Linear uses equal currency changes; equal-percentage uses approximately equal percentage changes.' }, { term: 'Equal cash / equal shares / Custom', explanation: 'Allocate similar all-in cash, similar shares, or enter every quantity directly.' }, { term: 'Precision and fees', explanation: 'Share precision, price precision, and percentage or fixed fees control generated rows.' }, { term: 'Include current position', explanation: 'Includes the saved position when displaying cumulative averages.' }, { term: 'Unallocated remainder / maximum capital requirement', explanation: 'Cash left after permitted rounded orders, and the highest cash needed before later sales return money.' }], 'Controls and outputs'),
    example('Equal-cash ladder', [{ label: 'Current position', value: '20 shares at $50' }, { label: 'All-in budget', value: '$1,000' }, { label: 'Prices', value: '$40, $35, $30' }, { label: 'Distribution', value: 'Equal cash' }, { label: 'Buy fee / precision', value: '0.2% / whole shares' }]),
    example('Level 1 at $40', [{ label: 'Shares', value: '8' }, { label: 'Gross / fee / total', value: '$320 / $0.64 / $320.64' }, { label: 'Running average', value: 'about $47.17' }]),
    example('Level 2 at $35', [{ label: 'Shares', value: '9' }, { label: 'Gross / fee / total', value: '$315 / $0.63 / $315.63' }, { label: 'Running average', value: 'about $44.22' }]),
    example('Level 3 at $30', [{ label: 'Shares', value: '11' }, { label: 'Gross / fee / total', value: '$330 / $0.66 / $330.66' }, { label: 'Final average', value: 'about $40.98' }, { label: 'Total used / unallocated', value: 'about $966.93 / $33.07' }]),
    note('The $33.07 is not automatically spent because whole-share rounding and per-order fees prevent another complete share from fitting within the allocation.'),
    paragraph('Generated rows remain scenario planning data. Editing a row changes that scenario’s calculation. Mark rows Executed to record what happened, then use Apply Executed Transactions separately if the saved position must be updated.'),
  ] }),
  topic({ slug: 'saved-scenarios', title: 'Saved Scenarios', group: 'Advanced planning', summary: 'Manage browser-local scenario records attached to the active position.', keywords: ['saved scenario', 'draft', 'active', 'completed', 'archived', 'load', 'duplicate', 'restore', 'delete', 'compare'], relatedSection: 'saved-scenarios', blocks: [
    results([{ term: 'Draft', explanation: 'A scenario still being worked on.' }, { term: 'Active', explanation: 'A scenario available for ordinary comparison.' }, { term: 'Completed', explanation: 'A recorded finished idea; it remains a browser-local scenario.' }, { term: 'Archived', explanation: 'Stored but hidden from ordinary comparison until restored.' }, { term: 'Load / Duplicate', explanation: 'Open the scenario or create a separate copy before trying a different idea.' }, { term: 'Archive / Restore / Delete', explanation: 'Hide, return, or remove a scenario deliberately. Delete removes it from this browser.' }]),
    paragraph('Scenarios belong to the position they were created for. Two scenarios can have the same name and remain separate records.'),
  ] }),
  topic({ slug: 'scenario-comparison', title: 'Scenario comparison', group: 'Advanced planning', summary: 'Compare up to four non-archived scenario outcomes without ranking them as recommendations.', keywords: ['scenario comparison', 'total buys', 'total sales', 'total fees', 'final shares', 'final basis', 'market value', 'invested capital', 'cash released', 'maximum capital'], relatedSection: 'comparison', blocks: [
    results([{ term: 'Total buys / total sales / total fees', explanation: 'The planned gross flows and fees across the scenario.' }, { term: 'Final shares / cost basis / average', explanation: 'The resulting position after scenario rows.' }, { term: 'Market value / realized P/L / unrealized P/L / break-even', explanation: 'Outcome estimates at the scenario price and configured Sell fee.' }, { term: 'Invested capital / cash released', explanation: 'Cash committed to buys and cash returned by sales.' }, { term: 'Maximum capital requirement', explanation: 'The highest amount of cash needed at any point before later sales return money.' }]),
    example('Compare trade-offs', [{ label: 'Scenario A', value: 'Adds $1,000; final average $47; maximum cash requirement $1,000' }, { label: 'Scenario B', value: 'Adds $4,000; final average $43; maximum cash requirement $4,000' }], 'Scenario B has a lower average, but it also requires more cash and creates more exposure.'),
    note('The comparison displays arithmetic trade-offs. It does not identify a better scenario.'),
  ] }),
  topic({ slug: 'reverse-sell', title: 'Reverse Sell Planner', group: 'Advanced planning', summary: 'Solve a required sale price from quantity, or a minimum permitted quantity from price.', keywords: ['reverse sell', 'solve price', 'solve shares', 'net proceeds', 'realized profit', 'oversell', 'share increment'], relatedSection: 'reverse-sell', blocks: [
    example('Solve price from quantity', [{ label: 'Shares to sell', value: '20' }, { label: 'Target', value: '$200 realized profit' }, { label: 'Result', value: 'Required sale price after the configured Sell fee' }]),
    example('Solve quantity from price', [{ label: 'Sale price', value: '$60' }, { label: 'Target', value: '$1,000 net proceeds' }, { label: 'Result', value: 'Minimum permitted share quantity' }]),
    results([{ term: 'Rounding upward', explanation: 'A solved quantity is rounded up to the share increment so it can meet the currency target.' }, { term: 'Available shares', explanation: 'A result cannot sell more than the scenario position has at that point.' }, { term: 'Impossible targets', explanation: 'A fee or entered price can make a target unreachable.' }, { term: 'Return at a known price', explanation: 'The calculator reports the achieved return instead of inventing a different quantity.' }, { term: 'Profit amount and percentage', explanation: 'Selling more shares can increase currency profit without changing profit percentage per share.' }]),
  ] }),
  topic({ slug: 'stress-tests', title: 'Stress tests', group: 'Advanced planning', summary: 'Compare one scenario at manual what-if prices; stress points are not forecasts.', keywords: ['stress test', 'absolute price', 'percentage change', 'market value', 'break-even distance', 'sort', 'reset defaults'], relatedSection: 'stress-tests', blocks: [
    example('Manual stress prices', [{ label: 'Scenario market price', value: '$50' }, { label: 'Stress points', value: '−30%, −10%, current, +10%, +30%' }, { label: 'Resolved prices', value: '$35, $45, $50, $55, $65' }]),
    results([{ term: 'Absolute price / percentage change', explanation: 'Enter an exact price or a change from the positive scenario market price.' }, { term: 'Current point', explanation: 'The scenario market price without a percentage change.' }, { term: 'Market value, P/L, return', explanation: 'The final position’s value and realized, unrealized, total, and return estimates.' }, { term: 'Break-even distance', explanation: 'How far the resolved price is from the scenario’s break-even estimate.' }, { term: 'Sort and reset', explanation: 'Change display order or restore the default points.' }]),
    warning('Stress tests are manual what-if prices, not market forecasts. Percentage points need a positive scenario market price.'),
  ] }),
  topic({ slug: 'executed-transactions', title: 'Executed transactions', group: 'Advanced planning', summary: 'Record actual trades in a scenario and review a complete preview before changing the saved position.', keywords: ['planned', 'executed', 'cancelled', 'applied', 'actual fee override', 'skipped rows', 'apply executed transactions', 'oversell'], relatedSection: 'executed-transactions', blocks: [
    results([{ term: 'Planned', explanation: 'An order being considered.' }, { term: 'Executed', explanation: 'A trade that actually happened.' }, { term: 'Cancelled', explanation: 'A planned order that did not happen.' }, { term: 'Applied', explanation: 'An executed row already used to update the saved position.' }, { term: 'Rows to apply', explanation: 'Executed trades that are valid and have not already been applied.' }, { term: 'Skipped rows', explanation: 'Rows that are Planned, Cancelled, or already Applied.' }, { term: 'Actual fee override', explanation: 'The final currency fee charged by the broker, used instead of the planned fee.' }], 'Plain status definitions'),
    steps(['Open a scenario and mark the trade Executed.', 'Enter actual price and quantity if they differ from the plan.', 'Enter the actual fee if known, plus execution date and optional broker or note.', 'Open Apply Executed Transactions.', 'Review included and skipped rows, then check resulting shares, average, fees, proceeds, and realized P/L.', 'Confirm only when the preview is correct.'], 'Complete workflow'),
    warning('Applying changes the saved position. The update is all-or-nothing: one invalid oversell blocks the whole operation. Already-applied rows cannot be applied twice, and scenario history remains visible afterward.'),
  ] }),
  topic({ slug: 'backup-export', title: 'Backup and exports', group: 'Your data', summary: 'Keep a complete JSON backup and use readable CSV exports for viewing or analysis.', keywords: ['backup', 'json', 'plan csv', 'scenario csv', 'dca ladder csv', 'merge', 'replace', 'import preview', 'collision'], relatedSection: 'data-management', blocks: [
    results([{ term: 'JSON backup', explanation: 'Complete application backup for later restoration.' }, { term: 'Plan CSV', explanation: 'Readable export of the ordinary future plan.' }, { term: 'Scenario CSV', explanation: 'Readable export of a saved scenario.' }, { term: 'DCA Ladder CSV', explanation: 'Readable export of ladder levels.' }]),
    paragraph('CSV files cannot currently be imported. Use JSON for restoring browser-local calculator data.'),
    results([{ term: 'Merge', explanation: 'Keeps current browser data, adds imported positions and scenarios, resolves internal ID collisions safely, and does not silently overwrite matching records.' }, { term: 'Replace', explanation: 'Removes current browser-local calculator data and replaces it with the selected backup after explicit confirmation.' }, { term: 'Import preview', explanation: 'Shows positions, ordinary-plan rows, scenarios, scenario rows, executed rows, and applied rows before you choose an action.' }], 'Import choices'),
    warning('Replace removes current browser-local data. Export a current JSON backup first if you may need to undo the replacement.'),
  ] }),
  topic({ slug: 'privacy', title: 'Browser storage and privacy', group: 'Your data', summary: 'Know where portfolio records are kept and what a browser backup protects.', keywords: ['privacy', 'localStorage', 'browser storage', 'incognito', 'github pages', 'device', 'portfolio backend'], relatedSection: 'data-management', blocks: [
    paragraph('Portfolio records remain in browser localStorage for this website. The application has no portfolio account and no portfolio backend.'),
    results([{ term: 'Website delivery', explanation: 'GitHub serves the website files and receives ordinary website requests.' }, { term: 'Portfolio records', explanation: 'The calculator does not upload saved portfolio records to a portfolio server.' }, { term: 'Browser and device', explanation: 'Another browser, profile, or device has separate data.' }, { term: 'Private sessions and clearing data', explanation: 'Private or incognito data may be temporary, and clearing website storage can remove saved data.' }]),
    note('Export JSON before clearing site data, changing devices, or relying on a browser as your only copy.'),
  ] }),
  topic({ slug: 'glossary', title: 'Glossary', group: 'Your data', summary: 'Individual plain-language definitions for calculator labels and planning terms.', keywords: ['position', 'shares', 'average price', 'cost basis', 'gross value', 'percentage fee', 'fixed fee', 'net proceeds', 'scenario workspace', 'cash released'], relatedSection: 'position', blocks: [
    { type: 'definitions', items: [
      { term: 'Position', definition: 'A saved record of one holding and its calculator settings.' }, { term: 'Shares', definition: 'The quantity currently owned or used in a calculation.' }, { term: 'Average price', definition: 'Cost basis divided by shares still owned.' }, { term: 'Cost basis', definition: 'The assigned cost of shares still owned, including configured Buy fees.' }, { term: 'Current market price', definition: 'A manual price used for estimates; it is not fetched live.' }, { term: 'Market value', definition: 'Shares multiplied by the entered current market price.' }, { term: 'Gross value', definition: 'Price × quantity before a fee.' }, { term: 'Fee', definition: 'The entered trading charge used in arithmetic.' }, { term: 'Percentage fee', definition: 'A percentage of gross value, such as 0.2%.' }, { term: 'Fixed fee', definition: 'One entered currency amount for the transaction.' }, { term: 'Total paid', definition: 'A Buy’s gross value plus fee.' }, { term: 'Net proceeds', definition: 'A Sell’s gross value minus fee.' }, { term: 'Realized P/L', definition: 'Gain or loss on shares sold after the Sell fee.' }, { term: 'Unrealized P/L', definition: 'Estimated gain or loss on shares still owned at an entered market price.' }, { term: 'Break-even', definition: 'Estimated fee-aware price where net proceeds cover cost basis.' }, { term: 'Target average', definition: 'The desired average after a calculated Buy.' }, { term: 'DCA', definition: 'Dividing a planned purchase into smaller staged orders.' }, { term: 'DCA level', definition: 'One ladder price, share quantity, and fee setting.' }, { term: 'Share increment', definition: 'The smallest permitted quantity, such as 1 or 0.01.' }, { term: 'Scenario', definition: 'A named browser-local planning sandbox attached to a position.' }, { term: 'Scenario workspace', definition: 'The scenario currently open in the planner.' }, { term: 'Ordinary future plan', definition: 'A hypothetical sequence attached to the saved position.' }, { term: 'Scenario status', definition: 'Draft, Active, Completed, or Archived state for organizing scenarios.' }, { term: 'Stress test', definition: 'A manual what-if price used to compare a scenario outcome.' }, { term: 'Planned transaction', definition: 'An order being considered.' }, { term: 'Executed transaction', definition: 'A trade recorded as having happened.' }, { term: 'Cancelled transaction', definition: 'A planned order that did not happen.' }, { term: 'Applied transaction', definition: 'An executed row already used to update the saved position.' }, { term: 'Unallocated remainder', definition: 'Cash that cannot buy another permitted increment within a ladder allocation.' }, { term: 'Maximum capital requirement', definition: 'The highest cash needed before later sales return money.' }, { term: 'Gross buys', definition: 'The total Buy value before fees.' }, { term: 'Cash released', definition: 'Cash returned by sales after their fees.' },
    ] },
  ] }),
];

export const helpGroups: HelpGroup[] = ['New users', 'Understand your position', 'Advanced planning', 'Your data'];

export function findHelpTopic(slug: string): HelpTopic | undefined {
  return helpTopics.find((item) => item.slug === slug);
}

export function helpTopicSearchText(topic: HelpTopic): string {
  const blockText = topic.blocks.flatMap((block) => {
    if (block.type === 'paragraph') return [block.text];
    if (block.type === 'note' || block.type === 'warning') return [block.title ?? '', block.text];
    if (block.type === 'steps') return [block.title ?? '', ...block.items];
    if (block.type === 'mistakes') return block.items;
    if (block.type === 'example') return [block.title, block.intro ?? '', ...(block.text ?? []), ...(block.rows ?? []).flatMap((row) => [row.label, row.value])];
    if (block.type === 'result-list') return [block.title ?? '', ...block.items.flatMap((item) => [item.term, item.explanation])];
    if (block.type === 'definitions') return block.items.flatMap((item) => [item.term, item.definition]);
    if (block.type === 'topics') return [block.title ?? '', ...block.slugs];
    return [];
  });
  return [topic.title, topic.summary, ...topic.keywords, ...blockText].join(' ').toLowerCase();
}
